# -*- coding: utf-8 -*-
"""ExercicioCap4(parte1/2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_ynkEYYMQpcGuNbOTZyfLG5EFiguzg2
"""

import numpy as np

#Nome: Kevin Lopes Do vale
#Exercicio 1

arr1=np.ones(8)
arr2=np.random.randint(0,10,8)

arr3 = arr1 + arr2
soma = arr3.sum()
if soma >= 40:
    matriz = arr3.reshape(2, 4)
    print("matriz de mais linhas doq colunas")
else:
    matriz = arr3.reshape(4, 2)
    print("matriz de mais colunas doq linhas")

#exercicio 2

arr1=np.arange(0, 52,1)
arr2=np.arange(100, 49,-1)

arr_concat= np.concatenate((arr1, arr2)) #concatene
arr_ordenado = np.sort(arr_concat) #ordenando
print(arr_concat)
print(arr_ordenado) #resultados ordenados

#exercicio 3

mtz= np.zeros(4).reshape(2,2)

posicao = np.random.randint(0,4) #sorteando a posição da matriz
mtz.reshape(4)[posicao]=1 #adicionando a posição sorteada como 1

tentativas = 0
escolhidas = [] # para nao burlar no joguinho
print('escolha uma posição entre entre 0 - 3')

while tentativas < 3:

    escolha = int(input('escolha uma posição: '))
    if escolha in escolhidas:
        print("Essa posição já foi escolhida hehe. Tente novamente.")
        continue

    escolhidas.append(escolha)

    if mtz.reshape(4)[escolha] == 1:  #acessando como vetor
        print("Game Over! :( Try Again.")
        break
    else:
        print("+1!")
        tentativas += 1

if tentativas == 3:
    print("Congratulations! You beat the game! :)")

#exercicio 4

matriz = np.random.randint(0,10,(4,4))
linhas = matriz.shape[0]  #numero de linhas
colunas = matriz.shape[1] #numero de colunas

total = linhas * colunas

if total % 2 == 0:
  print('Poderia se tornar um vetor unidimensional com numeros pares de elementos')
else:
  print('Poderia se tornar um vetor unidimensional com numeros impares de elementos')

#exercicio 5
np.random.seed(10)

matriz = np.random.randint(1,51,(4,4))

medialinhas = matriz.mean(axis=1) #media das linhas
mediacolunas = matriz.mean(axis=0) #media das colunas


print(medialinhas)
print(mediacolunas)
print(medialinhas.max()) #max linha
print(mediacolunas.max()) #max coluna

valores,contagens = np.unique(matriz, return_counts=True)
print(np.unique(matriz, return_counts=True)) # numeros que aparecem e se repetem
print("Números que aparecem 2 vezes:")
print(valores[contagens == 2])  #numeros que aparecem 2 vezes